import mixpanel from 'mixpanel-browser'

const ISSERVER = typeof window === 'undefined'

const API_KEY = process.env.NEXT_PUBLIC_MIXPANEL_KEY
mixpanel.init(API_KEY)

// let env = process.env.NODE_ENV === 'production';
let enabled = !!API_KEY

let user = {
  username: null,
}

if (!ISSERVER) {
  user = JSON.parse(localStorage.getItem('user'))
}

const { username } = user || {}

let actions = {
  identify: (id?) => {
    if (enabled) mixpanel.identify(id)
  },
  setUserData: (key, value) => {
    if (enabled) mixpanel.people.set({ [key]: value })
  },
  alias: (id?) => {
    if (enabled) mixpanel.alias(id)
  },
  track: (name, props?) => {
    if (enabled)
      mixpanel.track(name, {
        ...props,
        utm_source: 'organic',
        ...(!!username && { user_id: username }),
      })
  },
  people: {
    set: (props) => {
      if (enabled) mixpanel.people.set(props)
    },
  },
}

export const Mixpanel = actions

export const MixpanelEvents = {
  NAV_LINK_CLICK: 'NAV_LINK_CLICK',
  BURN_TOKEN: 'BURN_TOKEN',
  CANCEL_SALE: 'CANCEL_SALE',
  CANCEL_AUCTION: 'CANCEL_AUCTION',
  UPDATE_TOKEN_SALE_PRICE: 'UPDATE_TOKEN_SALE_PRICE',
  UPDATE_TOKEN_AUCTION_PRICE: 'UPDATE_TOKEN_AUCTION_PRICE',
  SELECTED_NFT_MARKET: 'SELECTED_NFT_MARKET',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET: 'WALLET',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP_PAGE_VIEW: 'SIGN_UP_PAGE_VIEW',
  PRODUCT_DETAIL_VIEW: 'PRODUCT_DETAIL_VIEW',
  OPEN_SEARCH: 'OPEN_SEARCH',
  SHARE_ON_FACEBOOK: 'SHARE_ON_FACEBOOK',
  SHARE_ON_TWITTER: 'SHARE_ON_TWITTER',
  VIEW_ON_IPFS: 'VIEW_ON_IPFS',
  VIEW_ON_BSC_SCAN: 'VIEW_ON_BSC_SCAN',
  CREATE_NFT_CLICK: 'CREATE_NFT_CLICK',
  BUY_NFT_CLICK: 'BUY_NFT_CLICK',
  BUY_NFT_PAGE_VIEW: 'BUY_NFT_PAGE_VIEW',
  ERROR_WHILE_BUYING: 'ERROR_WHILE_BUYING',
  UPLOAD_NFT_CLICK: 'UPLOAD_NFT_CLICK',
  SAVE_MINTING_TX: 'SAVE_MINTING_TX',
  NFT_MINTED: 'NFT_MINTED',
  NFT_ESCROWED: 'NFT_ESCROWED',
  NFT_LISTED_ON_SALE: 'NFT_LISTED_ON_SALE',
  NFT_CREATION_COMPLETE: 'NFT_CREATION_COMPLETE',
  NFT_CREATION_ERROR: 'NFT_CREATION_ERROR',
  META_MASK_CONNECTED: 'META_MASK_CONNECTED',
  HOME_PAGE_VIEW: 'HOME_PAGE_VIEW',
  SIGN_IN_CONFIRMED: 'SIGN_IN_CONFIRMED',
  SIGN_UP_CONFIRMED: 'SIGN_UP_CONFIRMED',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  NFT_VIEWED: 'NFT_VIEWED',
  PROFILE_VIEW_OTHER_USER: 'PROFILE_VIEW_OTHER_USER',
  SIGN_UP_COLLECT_CLICK: 'SIGN_UP_COLLECT_CLICK',
  NFT_PURCHASED: 'NFT_PURCHASED',
  BUY_NFT_LOW_BALANCE: 'BUY_NFT_LOW_BALANCE',
  BECOME_CREATOR: 'BECOME_CREATOR',
  VIEW_PROOF_OF_AUTHENCITY_CALLED: 'VIEW_PROOF_OF_AUTHENCITY_CALLED',
  BUY_CRYPTO_WITH_FIAT_CLICK: 'BUY_CRYPTO_WITH_FIAT_CLICK',
  SORT_LISTING: 'SORT_LISTING',
  FILTER_LISTING: 'FILTER_LISTING',
  LOG_OUT_USER: 'LOG_OUT_USER',
  FOOTER_LINKS_CLICK: 'FOOTER_LINKS_CLICK',
  SEARCH_EVENT: 'SEARCH_EVENT',
  SHARE_CONTENT_CLICKED: 'SHARE_CONTENT_CLICKED',
  PROFILE_VIEW_SELF: 'PROFILE_VIEW_SELF',
  PLACE_BID: 'PLACE_BID',
  PLACE_BID_PAGE_VIEW: 'PLACE_BID_PAGE_VIEW',
  BUY_TOKEN_PAGE_VIEW: 'BUY_TOKEN_PAGE_VIEW',
  PLACE_BID_INPUT_CHANGE: 'PLACE_BID_INPUT_CHANGE',
  PLACE_BID_SUCCESS: 'PLACE_BID_SUCCESS',
  PLACE_BID_FAILURE: 'PLACE_BID_FAILURE',
  SETTLE_AUCTION: 'SETTLE_AUCTION',
  SETTLE_AUCTION_ERROR: 'SETTLE_AUCTION_ERROR',
  NFT_LISTED_ON_AUCTION: 'NFT_LISTED_ON_AUCTION',
  FOLLOW_USER: 'FOLLOW_USER',
  UN_FOLLOW_USER: 'UN_FOLLOW_USER',
  REPORT_CONTENT_CLICKED: 'REPORT_CONTENT_CLICKED',
  UPLOAD_PROFILE_PHOTO: 'UPLOAD_PROFILE_PHOTO',
  UPLOAD_COVER_PHOTO: 'UPLOAD_COVER_PHOTO',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  READ_MORE_CLICKED: 'READ_MORE_CLICKED',
  VIEW_ALL_TRENDING_AUCTIONS: 'VIEW_ALL_TRENDING_AUCTIONS',
  VIEW_ALL_TRENDING_NFTS: 'VIEW_ALL_TRENDING_NFTS',
  VIEW_ALL_GENESIS_NFTS: 'VIEW_ALL_GENESIS_NFTS',
  VIEW_ALL_TRENDING_COLLECTIONS: 'VIEW_ALL_TRENDING_COLLECTIONS',
  VIEW_ALL_TRENDING_CREATORS: 'VIEW_ALL_TRENDING_CREATORS',
  VIEW_ALL_TRENDING_COLLECTORS: 'VIEW_ALL_TRENDING_COLLECTORS',
  READ_COLLECTOR_GUIDELINE: 'READ_COLLECTOR_GUIDELINE',
  READ_CREATOR_GUIDELINE: 'READ_CREATOR_GUIDELINE',

  HOME_PAGE_CREATE_NFT_CLICK: 'HOME_PAGE_CREATE_NFT_CLICK',
  HOME_PAGE_DISCOVER: 'HOME_PAGE_DISCOVER',
  SOCIAL_MEDIA_LINK_CLICK: 'SOCIAL_MEDIA_LINK_CLICK',
  BANNER_IMAGE_CLICK: 'BANNER_IMAGE_CLICK',

  MAKE_OFFER_VIEW: 'MAKE_OFFER_VIEW',
  MAKE_OFFER_CLICK: 'MAKE_OFFER_CLICK',
  ACCEPT_OFFER: 'ACCEPT_OFFER',
  ACCEPT_OFFER_ERROR: 'ACCEPT_OFFER_ERROR',
  CANCEL_OFFER: 'CANCEL_OFFER',
  CANCEL_ACCEPTED_OFFER: 'CANCEL_ACCEPTED_OFFER',
  CANCEL_ACCEPTED_OFFER_ERROR: 'CANCEL_ACCEPTED_OFFER_ERROR',
  SETTLE_OFFER: 'SETTLE_OFFER',
  SETTLE_OFFER_ERROR: 'SETTLE_OFFER_ERROR',

  //collections
  COLLECTIONS_FILTER: 'COLLECTIONS_FILTER',
  COLLECTION_PROFILE_VIEW: 'COLLECTION_PROFILE_VIEW',
  ACTIVITY_CLICK: 'ACTIVITY_CLICK',
  RANKINGS_CLICK: 'RANKINGS_CLICK',

  COLLECTION_PROFILE_SELECTED_TAB: 'COLLECTION_PROFILE_SELECTED_TAB',

  CREATE_COLLECTION_CLICK: 'CREATE_COLLECTION_CLICK',
  VIEW_COLLECTION_CLICK: 'VIEW_COLLECTION_CLICK',
  RANKINGS_DURATION_CLICK: 'RANKINGS_DURATION_CLICK',

  CREATE_COLLECTION_SUCCESS: 'CREATE_COLLECTION_SUCCESS',
  CREATE_COLLECTION_ERROR: 'CREATE_COLLECTION_ERROR',

  EXTERNAL_COLLECTION_MINT: 'EXTERNAL_COLLECTION_MINT',
  EXTERNAL_COLLECTION_MINT_SUCCESS: 'EXTERNAL_COLLECTION_MINT_SUCCESS',
  EXTERNAL_COLLECTION_MINT_ERROR: 'EXTERNAL_COLLECTION_MINT_ERROR',

  VIEW_ALL_LIVE_MINTING_NFTS: 'VIEW_ALL_LIVE_MINTING_NFTS',
  VIEW_ALL_UPCOMING_NFTS: 'VIEW_ALL_UPCOMING_NFTS',

  COLLECTIONS_CLICK: 'COLLECTIONS_CLICK',
  STATS_CLICK: 'STATS_CLICK',
  CHANGE_THEME: 'CHANGE_THEME',

  MINT_CLICKED: 'MINT_CLICKED',
  MINT_SUCCESS: 'MINT_SUCCESS',
  MINT_ERROR: 'MINT_ERROR',

  SUBMIT_YOUR_COLLECTION: 'SUBMIT_YOUR_COLLECTION',
  REQUEST_FEATURE: 'REQUEST_FEATURE',

  //website
  WEBSITE_LINKS: 'WEBSITE_LINKS',
}
