export const SHOW_SCROLL_TO_TOP = 'SHOW_SCROLL_TO_TOP'
export const HIDE_SCROLL_TO_TOP = 'HIDE_SCROLL_TO_TOP'
export const TOGGLE_FILTER = 'TOGGLE_FILTER'
export const SET_CARD_DISPLAY_FRAME = 'SET_CARD_DISPLAY_FRAME'
